# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_image',
            field=models.ImageField(default='collections_pic/images/no-name.jpg', upload_to='images/collections_pic/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='imagesrestaurant_pic/no-name.jpg', upload_to='images/restaurant_pic/'),
        ),
    ]
