# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170116_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='OpeningTime',
            new_name='Time',
        ),
    ]
