# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170116_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='RestaurantTiming',
        ),
        migrations.RenameModel(
            old_name='Day',
            new_name='WeekDay',
        ),
    ]
