# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170202_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_image_thumbnail',
            field=models.ImageField(default='images/collections_pic/thumbnails/no-name.jpg', upload_to='images/collections_pic/thumbnails/'),
        ),
    ]
