# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20170116_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='restaurant_pic_folder/None/no-img.jpg', upload_to='media/images/restaurant_pic_folder/'),
        ),
        migrations.AlterField(
            model_name='restauranttiming',
            name='available_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_day', to='restaurant.WeekDay'),
        ),
        migrations.AlterField(
            model_name='restauranttiming',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_timing', to='restaurant.Restaurant'),
        ),
    ]
