# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20170202_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_description',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
