# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_collection_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection_image',
            field=models.ImageField(default='images/categories_pic/no-name.jpg', upload_to='images/categories_pic/'),
        ),
    ]
