# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170117_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='restaurant_pic_folder/None/no-img.jpg', upload_to='media/images/restaurant_pic/'),
        ),
        migrations.AlterField(
            model_name='restauranttiming',
            name='available_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='restaurant.WeekDay'),
        ),
    ]
