# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20170118_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttiming',
            name='available_days',
        ),
        migrations.AddField(
            model_name='restauranttiming',
            name='week_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_day', to='restaurant.WeekDay'),
        ),
    ]
