# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20170118_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttiming',
            old_name='week_day',
            new_name='working_days',
        ),
    ]
