# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20170207_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image_thumbnail',
            field=models.ImageField(default='imagesrestaurant_pic/thumbnail/no-name.jpg', upload_to='images/restaurant_pic/thumbnail/'),
        ),
    ]
