# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_restaurant_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='locality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number_1',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='imagesrestaurant_pic/restaurant_image.jpg', upload_to='images/restaurant_pic/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image_thumbnail',
            field=models.ImageField(default='imagesrestaurant_pic/thumbnail/restaurant_image_thumbnail.jpg', upload_to='images/restaurant_pic/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
