# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20170118_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
            ],
            options={
                'default_related_name': 'collections',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='restaurant_pic/images/no-name.jpg', upload_to='images/restaurant_pic/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='restaurant',
            field=models.ManyToManyField(related_name='collections', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ManyToManyField(related_name='categories', to='restaurant.Restaurant'),
        ),
    ]
