# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20170207_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='images/restaurant_pic/restaurant_image.jpg', upload_to='images/restaurant_pic/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image_thumbnail',
            field=models.ImageField(default='images/restaurant_pic/thumbnail/restaurant_image_thumbnail.jpg', upload_to='images/restaurant_pic/thumbnail/'),
        ),
    ]
