# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20170205_0020'),
        ('restaurant', '0011_auto_20170207_1430'),
    ]

    operations = [
    ]
