# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_merge_20170211_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('menu_image', models.ImageField(default='images/menu_pic/menu.jpg', upload_to='images/menu_pic/')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'default_related_name': 'menu',
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_thumbnail_image',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='images/restaurant_pic/restaurant_image.jpg', upload_to='images/restaurant_pic/'),
        ),
        migrations.AddField(
            model_name='menuimage',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.Restaurant'),
        ),
    ]
