# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20170213_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuimage',
            name='menu_name',
        ),
    ]
