# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20170213_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={},
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='cuisine',
            name='restaurant',
            field=models.ManyToManyField(to='restaurant.Restaurant'),
        ),
    ]
