# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20170215_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisines'},
        ),
    ]
